# Generated by Django 3.0.3 on 2020-05-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200529_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField()),
            ],
        ),
    ]
